### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by MatthiasLohr** [cburgdorf/rusty-rlp#19]
Hey,

any chance that you could create and upload a cp39 version to PyPI? Thanks in advance!

Best regards
Matthias

**Comment by cburgdorf** [comment]
It should be fairly simple to add support for Python 3.9 (see https://github.com/cburgdorf/rusty-rlp/pull/20) but I [ran into an issue with the Windows build](https://github.com/cburgdorf/rusty-rlp/pull/20/checks?check_run_id=1307805212). If you care strongly about Python 3.9 support, maybe you could look into this?

Just being curious, are you facing any installation issues with *other libraries* where this comes up? Because we recently made rusty-rlp optional so there shouldn't be any installation issues coming from installing other libraries such as web3.py etc. But of course, you may want to install rusty-rlp standalone on a Python 3.9 system for plenty of valid reasons..

**Comment by MatthiasLohr** [comment]
Sorry for my late response, I was busy with a lot of other stuff, now I can get back to these kind of things.

Unfortunately, I don't have any experience with windows environments (I'm spending 99.9% of my PC time on debian based linux such as Ubuntu, Debian, Raspian, etc.) - and the logs in your link are gone by now.

What exactly do you mean with "installation issues with other libraries"? I'm not using the library directly, but some libraries in the ethereum context (web3, eth-tester, py-evm).

**Comment by cburgdorf** [comment]
>I'm not using the library directly, but some libraries in the ethereum context (web3, eth-tester, py-evm).

This shouldn't be an issue anymore because no library (that I know of) depends on this directly. It has to be explicitly configured as a dependency to be pulled in as an extra performance improvement. Do you see failed installs for any project because of this library?

**Comment by pacrob** [comment]
closed by #20
